// Automatically generated by GitVersioner 0.0.48.164 (0x57EE7216)

#include "version.hpp"

namespace samples2cams
{
    const unsigned AtracsysGitVersion::Major( 2 );
    const unsigned AtracsysGitVersion::Minor( 0 );
    const unsigned AtracsysGitVersion::Revision( 1 );
    const unsigned AtracsysGitVersion::Build( 305 );
    const unsigned AtracsysGitVersion::TimeStamp( 0x585923A0 );
    const std::string AtracsysGitVersion::SoftwareVersion( "2.0.1.305" );
    const std::string AtracsysGitVersion::SoftwareVersionFull( "2.0.1.305 (0x585923A0)" );
}
